version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-219-52-220.compute-1.amazonaws.com
            port: '5432'
            database: d58vl3gr56lrn8
            ssl: true
            user: nwgkuzjadtsfep
            password: 009ce279badeb15fd683256f5129adfe945dbc7002199e58c5cff87265a87c4a
            migrations: true